
# Configuration parameters
website_url: https://mouadfiali.github.io/recaptcha-example/

# Prompt
prompt-template: "Analyze the provided image, which is segmented into a grid. The actual image is of size {grid_size}. Your task is to identify and list the cells' numbers that contain '{object}'. This object may blend in with its surroundings or have similar colors to other elements in the image, necessitating detailed scrutiny. List the cells' numbers that contain the object, providing a concise, comma-separated sequence of numbers without additional commentary. Ensure the accuracy of the cell numbers in your response."


# Add your own chrome user data directory here
#user-data-dir: !env USER_DATA_DIR
user-data-dir: C:\Users\mouad\AppData\Local\Google\Chrome\User Data

# Add your own profile directory here
#profile-directory: !env PROFILE_DIR
profile-directory: Profile 5
